### ISSUE TITLE
Invalid attribute, translate

### ISSUE THREAD

**Issue by MikeVlad6** [eldest-daughter/ed-questionnaire#23]
Hi, this is probably a newbie question but i was trying to implement your project and i can't get past this error: 

```
C:\Users\user\Desktop\New project\mysite>python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-pa
ckages\django\core\management\__init__.py", line 364, in execute_from_command_li
ne
    utility.execute()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-pa
ckages\django\core\management\__init__.py", line 338, in execute
    django.setup()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-pa
ckages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-pa
ckages\django\apps\registry.py", line 108, in populate
    app_config.import_models()
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-pa
ckages\django\apps\config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\importl
ib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-pa
ckages\ed_questionnaire-2.0.1-py3.6.egg\questionnaire\models.py", line 93, in <m
odule>
    class QuestionSet(models.Model):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-pa
ckages\django\db\models\base.py", line 124, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-pa
ckages\django\db\models\base.py", line 325, in add_to_class
    value.contribute_to_class(cls, name)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-pa
ckages\django\db\models\options.py", line 206, in contribute_to_class
    raise TypeError("'class Meta' got invalid attribute(s): %s" % ','.join(meta_
attrs.keys()))
TypeError: 'class Meta' got invalid attribute(s): translate
```
I did a little research on Meta but since i haven't used it so far i can't point out the problem, maybe you could help me.

Thank you!

**Comment by MikeVlad6** [comment]
Did fix it [this ](https://stackoverflow.com/questions/1088431/adding-attributes-into-django-models-meta-class)way but i reckon it can't be a permanent solution.

**Comment by gcaprio** [comment]
Hi @MikeVlad6 ,

This project isn't being actively maintained. Depending on the version of Django you're using, it may not be support. Very sorry for the news.
